### ISSUE TITLE
Reflect inputs/outputs on PyBpod emulator GUI

### ISSUE THREAD

**Issue by HenryJFlynn** [Poirazi-Lab/mouse2afc#6]
#### Background:
In the MATLAB protocol, if a mouse pokes in/out or a light or valve is triggered, that change is reflected in the Bpod console. That does not happen with the equivalent emulator GUI in PyBpod. The PyBpod emulator can cause changes to the hardware (if the user pokes with the emulator, the software interprets it as if the mouse poked) but changes on the hardware cannot cause a change in the emuator

Bpod console:
![image](https://github.com/Poirazi-Lab/mouse2afc/assets/130571023/ea1b69e1-dd6a-45f4-bb11-58d05308ef38)

Pybpod emulator:
![image](https://github.com/Poirazi-Lab/mouse2afc/assets/130571023/61a2bf52-f6f8-4c32-ac59-b1bdfd253f3e)

#### Goal: 
Make the changes which happen on the experimental hardware also happen in the PyBpod GUI emulator, similar to the MATLAB feature

**Comment by stumpychloe** [comment]
When editing in "emulator_gui.py" specifically the definition "__button_on_click_evt" it causes the error "socket.error: [Errno 48] Address already in use". The issue with this error is that GUI cant detect what if different in the code that caused this so its difficult to fix.

**Comment by stumpychloe** [comment]
When the device is pluged into the computer it out puts this error when trying to load the board.

![image](https://github.com/Poirazi-Lab/mouse2afc/assets/166519539/4c4e7559-79d4-4d77-b5c8-f3b5a1363150)

**Comment by stumpychloe** [comment]
To fix the issue of "could not open port' I followed the first step of the installing and updating pybpod documentation by executing this line of code
"sudo usermod -a -G dialout [your username]" then restarting the computer 

After restarting and running the bpod this error occurred when trying to load the board. 

![image](https://github.com/Poirazi-Lab/mouse2afc/assets/166519539/3e443786-7cd5-40e2-a7a2-205f3f30af0d)

**Comment by ckaraneen** [comment]
> When editing in "emulator_gui.py" specifically the definition "__button_on_click_evt" it causes the error "socket.error: [Errno 48] Address already in use". The issue with this error is that GUI cant detect what if different in the code that caused this so its difficult to fix.

Fixed by https://github.com/ckarageorgkaneen/pybpod-api/pull/5 :smiley:

**Comment by ckaraneen** [comment]
> To fix the issue of "could not open port' I followed the first step of the installing and updating pybpod documentation by executing this line of code "sudo usermod -a -G dialout [your username]" then restarting the computer
> 
> After restarting and running the bpod this error occurred when trying to load the board.
> 
> ![image](https://private-user-images.githubusercontent.com/166519539/325216296-3e443786-7cd5-40e2-a7a2-205f3f30af0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjE4NDMsIm5iZiI6MTcxMzk2MTU0MywicGF0aCI6Ii8xNjY1MTk1MzkvMzI1MjE2Mjk2LTNlNDQzNzg2LTdjZDUtNDBlMi1hN2EyLTIwNWYzZjMwYWYwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMjI1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzEwNDNlYjAwYWZjNDNhN2E3Yzk5MjRmMmZjOWMwNWUzMTczNDdkMGMyZTBhMmU4NGNiMDUzNmI0NzliYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LCO8SLHf8kBhvkik5M3mCGApkAzkOBBAG3ew0HteXWY)

Hmmm that's weird.

**Comment by stumpychloe** [comment]
pybpod protocol works when the device is plugged into its left port which resolves the issue of failed connectivity. While running the protocol You can input the pokes but you are unable to see what the correct choice is. This is because the GUI is not displaying which LED is clicked. I now want to make the GUI display the LED output and the valve output.

**Comment by ckaraneen** [comment]
> pybpod protocol works when the device is plugged into its left port which resolves the issue of failed connectivity. While running the protocol You can input the pokes but you are unable to see what the correct choice is. This is because the GUI is not displaying which LED is clicked. I now want to make the GUI display the LED output and the valve output.

Makes sense. Now just gotta figure out how to  make the device code communicate the data to the GUI emulator server like the emulator code does.

**Comment by stumpychloe** [comment]
After some digging I found where the data for the outputs is coming from by having a print statement that prints the channel name and value.

ex:
['stdout', '2024-04-25 11:43:32.706292', '', '', 'Output value: 3.0 Output name: PWM2', '']

I now plan to make the GUI to split this data and have it click the button the coordinates with the data like how its done in emulator mode.

**Comment by stumpychloe** [comment]
After going through the emulator mode client-server GUI code with @ckarageorgkaneen, these are the next steps:
- [x] Rename `EmulatorModeServer ` -> `EmulatorGUIServer` (and file)
- [x] Move emulator GUI client code from `Emulator` class into a new `EmulatorGUIClient` class (create new file)
- [x] Create `EmulatorGUIClient` object attribute in `Emulator` constructor (might need to pass in hardware, state, etc. objects)
- [x] Make it work with new object :smile_cat:

**Comment by stumpychloe** [comment]
Issue closed by https://github.com/ckarageorgkaneen/pybpod-api/pull/6 and https://github.com/ckarageorgkaneen/pybpod-gui-plugin-emulator/pull/1
