### ISSUE TITLE
Environment activation fails

### ISSUE THREAD

**Issue by notatimelord** [Poirazi-Lab/mouse2afc#7]
Following [GUIDE step 1](https://github.com/Poirazi-Lab/mouse2afc/blob/main/GUIDE.md#1-create-environment) does not lead to an activated conda environment as expected, after running:

```bash
activate pybpod-environment
```

which is probably because this way of activating an environment is outdated.

Furthermore, running the proper

```bash
conda activate pybpod-environment
```

yields the following error:

```
conda: error: argument command: invalid choice ...
```

**Comment by ckaraneen** [comment]
Fixed by #10.
